### ISSUE TITLE
New input file command line option

### ISSUE THREAD

**Issue by willcannings** [tzukuri/SwiftForest#2]
Add the ability to train a model on multiple input files, with each file storing training examples for a different output class. This enables creating models on training data that's split between multiple files, without requiring concatenation beforehand.

e.g --train class1,file_path --train class1,file_path --train class2,file_path

**Comment by mrtzukuri** [comment]
It is our pleasure to introduce Unlosable Glasses - beautifully handmade glasses that connect with your iPhone to help you remember them. To celebrate our launch - please enjoy an 85 AUD credit towards any pair until midnight Tuesday, 7 March.

To redeem this offer, simply enter the following promotional token when prompted during checkout:

😎

Free shipping. Free prescriptions. Free returns for 20 days.

Unlosable Glasses notify you when you've left them behind, remember where you've left them and show you how far away they are when you are searching for them.

'Seeking means having goal. Finding means being free, being open, having no goal.' Herman Hesse

Tzukuri Pty. Ltd.

Kensington, 2033, NSW, Australia.

If you have any questions, or you'd just like to say hi, please get in touch by replying to this email.                  Unsubscribe http://tzukuri.cmail19.com/t/d-u-hjkhtrd-xidlhikhu-d/

**Comment by mrtzukuri** [comment]
It is our pleasure to introduce Unlosable Glasses - beautifully handmade glasses that connect with your iPhone to help you remember them. To celebrate our launch - please enjoy an 85 AUD credit towards any pair until midnight Tuesday, 7 March.

To redeem this offer, simply enter the following promotional token when prompted during checkout:

😎

Free shipping. Free prescriptions. Free returns for 20 days.

Unlosable Glasses notify you when you've left them behind, remember where you've left them and show you how far away they are when you are searching for them.

'Seeking means having goal. Finding means being free, being open, having no goal.' Herman Hesse

Tzukuri Pty. Ltd.

Kensington, 2033, NSW, Australia.

If you have any questions, or you'd just like to say hi, please get in touch by replying to this email.                  Unsubscribe http://tzukuri.cmail19.com/t/d-u-hjkhtrd-xidlhiua-d/
