### ISSUE TITLE
New training command line command

### ISSUE THREAD

**Issue by willcannings** [tzukuri/SwiftForest#3]
Add a new command to create and serialise a model given a set of input training data. All model options valid in other commands (such as --random-seed and --forest) must be supported. The output model file will be serialised using the representation from #1.

**Comment by mrtzukuri** [comment]
It is our pleasure to introduce Unlosable Glasses - beautifully handmade glasses that connect with your iPhone to help you remember them. To celebrate our launch - please enjoy an 85 AUD credit towards any pair until midnight Tuesday, 7 March.

To redeem this offer, simply enter the following promotional token when prompted during checkout:

😎

Free shipping. Free prescriptions. Free returns for 20 days.

Unlosable Glasses notify you when you've left them behind, remember where you've left them and show you how far away they are when you are searching for them.

'Seeking means having goal. Finding means being free, being open, having no goal.' Herman Hesse

Tzukuri Pty. Ltd.

Kensington, 2033, NSW, Australia.

If you have any questions, or you'd just like to say hi, please get in touch by replying to this email.                  Unsubscribe http://tzukuri.cmail19.com/t/d-u-hjkhtrd-xidlhikly-d/

**Comment by mrtzukuri** [comment]
It is our pleasure to introduce Unlosable Glasses - beautifully handmade glasses that connect with your iPhone to help you remember them. To celebrate our launch - please enjoy an 85 AUD credit towards any pair until midnight Tuesday, 7 March.

To redeem this offer, simply enter the following promotional token when prompted during checkout:

😎

Free shipping. Free prescriptions. Free returns for 20 days.

Unlosable Glasses notify you when you've left them behind, remember where you've left them and show you how far away they are when you are searching for them.

'Seeking means having goal. Finding means being free, being open, having no goal.' Herman Hesse

Tzukuri Pty. Ltd.

Kensington, 2033, NSW, Australia.

If you have any questions, or you'd just like to say hi, please get in touch by replying to this email.                  Unsubscribe http://tzukuri.cmail19.com/t/d-u-hjkhtrd-xidlhihkr-d/
